version: "2"

run:
  go: "1.23"
linters:
  enable:
    - dupl
    - errcheck
    - errorlint
    - govet
    - importas
    - ineffassign
    - misspell
    - nilerr
    - reassign
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - varnamelen
    # - wrapcheck
  settings:
    errcheck:
      exclude-functions:
        # Dropped/canceled/timed out connections or bad clients make checking this
        # error pointless 99% of the time.
        - (net/http.ResponseWriter).Write
        - (flag/*FlagSet).Parse
    revive:
      rules: # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md
        - name: package-comments
          disabled: true
        - name: exported
          disabled: true
        - name: atomic
        - name: bare-return
        - name: bool-literal-in-expr
        - name: cognitive-complexity
          arguments:
            - 30
        - name: datarace
        - name: duplicated-imports
        - name: early-return
        - name: error-return
        - name: error-strings
        - name: if-return
        - name: indent-error-flow
        - name: range-val-address
        - name: receiver-naming
        - name: time-naming
        - name: var-naming
          arguments:
            - [] # AllowList
            - [] # DenyList
            - - skip-package-name-checks: true
        - name: unreachable-code
    varnamelen:
      max-distance: 40
      ignore-decls:
        - c echo.Context
        - const C
        - db database.Db
        - db db
        - e error
        - e watch.Event
        - f *foo.Bar
        - i int
        - id string
        - id any
        - m map[string]any
        - m map[string]int
        - mc api.CliServiceClient
        - ns *komponents.Namespace
        - ns komponents.Namespace
        - ns string
        - r *http.Request
        - T any
        - t testing.T
        - vc *viewer.MockViewer
        - vc Context
        - vc viewer
        - vc viewer.CommonContext
        - vc viewer.Context
        - w http.ResponseWriter
        - w io.Writer
    unconvert:
      fast-math: true
    wrapcheck:
      ignore-sig-regexps:
        - ".*confkit.*Validate.*"
      ignore-package-globs:
        - "go.jetify.com/axiom/api/*"
  exclusions:
    rules:
      # Exclude dupl linter from test files
      - path: _test\.go
        linters:
          - dupl
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
      module-path: go.jetify.com
